edition = "2021"
fn_args_layout = "Vertical"
match_arm_leading_pipes = "Preserve"
max_width = 100
reorder_modules = false
# tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

unstable_features = true
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 100
control_brace_style = "AlwaysNextLine"
empty_item_single_line = false
enum_discrim_align_threshold = 60
error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
# format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
# indent_style = "Visual"
# trailing_comma = "Never"
match_arm_blocks = false
match_block_trailing_comma = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
spaces_around_ranges = true
# space_before_colon = true
struct_field_align_threshold = 40
version = "Two"
wrap_comments = true
