# My personal settings that are applied globally (per-user) and with higher precedence than
# per-project-directory `.clangd` files.  This must only have settings that should be applied to
# *every* source file that `clangd` processes (but note: `If`-block conditions may be used to
# limit which settings here apply to which projects and files).  These settings will be merged
# with any provided by a project's `.clangd` file.
#
# This is intended to be placed (maybe via symlink) at ~/.config/clangd/config.yaml if desired.
#
# See: https://clangd.llvm.org/config

InlayHints:
  Enabled: Yes
  TypeNameLimit: 0

Hover:
  ShowAKA: Yes

---

If:
  PathMatch: [ '.*' ]
 #PathExclude: [ ... , ... ]

CompileFlags:
  Remove: [
    -Werror,
  ]
  Add: [
  ]

#---
#
# Sometimes helpful to manually tell `clangd` to use particular compiler flags (e.g. `-I/dir`,
# `-DFOO=bar`, `-m64`, etc.) for some project, when `compile_commands.json` can't be generated for
# it for some reason (i.e. when `bear` can't even be used), and when a `.clangd` file shouldn't be
# added in the project's directory.  A directory specified here with `CompilationDatabase:` must
# contain either `compile_commands.json` or `compile_flags.txt`, and you'd manually populate the
# contents of such file.
#
#If:
#  PathMatch: '(.*/)?something/special/.+'
#
#CompileFlags:
#  CompilationDatabase: ../my/clangd/something-special/
#
#---
