(((min-height . 12)
  (min-width . 20)
  (min-height-ignore . 7)
  (min-width-ignore . 8)
  (min-height-safe . 3)
  (min-width-safe . 4)
  (min-pixel-height . 276)
  (min-pixel-width . 220)
  (min-pixel-height-ignore . 161)
  (min-pixel-width-ignore . 88)
  (min-pixel-height-safe . 69)
  (min-pixel-width-safe . 44))
 vc
 (pixel-width . 2291)
 (pixel-height . 1358)
 (total-width . 208)
 (total-height . 59)
 (normal-height . 1.0)
 (normal-width . 1.0)
 (combination-limit)
 (hc
  (pixel-width . 2291)
  (pixel-height . 322)
  (total-width . 208)
  (total-height . 14)
  (normal-height . 0.23711340206185572)
  (normal-width . 1.0)
  (combination-limit)
  (leaf
   (pixel-width . 1147)
   (pixel-height . 322)
   (total-width . 104)
   (total-height . 14)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . gdb-locals-values-buffer))
   (buffer " *gdb-placeholder*"
           (selected)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated . t)
           (point . 1)
           (start . 1)))
  (leaf
   (last . t)
   (pixel-width . 1144)
   (pixel-height . 322)
   (total-width . 104)
   (total-height . 14)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . gdb-inferior-io))
   (buffer " *gdb-placeholder*"
           (selected)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated)
           (point . 1)
           (start . 1))))
 (hc
  (pixel-width . 2291)
  (pixel-height . 944)
  (total-width . 208)
  (total-height . 41)
  (normal-height . 0.6944342169857634)
  (normal-width . 1.0)
  (combination-limit)
  (leaf
   (pixel-width . 1147)
   (pixel-height . 944)
   (total-width . 104)
   (total-height . 41)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . source))
   (buffer " *gdb-placeholder*"
           (selected)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated)
           (point . 1)
           (start . 1))
   (prev-buffers
    ("*scratch*" 1 1)))
  (leaf
   (last . t)
   (pixel-width . 1144)
   (pixel-height . 944)
   (total-width . 104)
   (total-height . 41)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . command))
   (buffer " *gdb-placeholder*"
           (selected . t)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated)
           (point . 1)
           (start . 1))))
 (hc
  (last . t)
  (pixel-width . 2291)
  (pixel-height . 92)
  (total-width . 208)
  (total-height . 4)
  (normal-height . 0.06845238095238096)
  (normal-width . 1.0)
  (combination-limit)
  (leaf
   (pixel-width . 1147)
   (pixel-height . 92)
   (total-width . 104)
   (total-height . 4)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . gdb-stack-buffer))
   (buffer " *gdb-placeholder*"
           (selected)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated . t)
           (point . 1)
           (start . 1)))
  (leaf
   (last . t)
   (pixel-width . 1144)
   (pixel-height . 92)
   (total-width . 104)
   (total-height . 4)
   (normal-height . 1.0)
   (normal-width . 0.5)
   (parameters
    (gdb-buffer-type . gdb-breakpoints-buffer))
   (buffer " *gdb-placeholder*"
           (selected)
           (hscroll . 0)
           (fringes 8 8 nil nil)
           (margins nil)
           (scroll-bars nil 0 t nil 0 t nil)
           (vscroll . 0)
           (dedicated . t)
           (point . 1)
           (start . 1)))))
