;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-defun
        beginning-of-visual-line
        c-electric-semi&comma
        comment-dwim
        company-indent-or-complete-common
        delete-indentation
        dired-next-line
        dired-previous-line
        dired-tree-down
        dired-up-directory
        end-of-defun
        end-of-visual-line
        forward-sexp
        goto-line
        home-end-end
        home-end-home
        indent-for-tab-command
        kill-region
        markdown-cycle
        markdown-outdent-or-delete
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-next-sexp
        sp-remove-active-pair-overlay
        wdired--self-insert
        wdired-next-line
        wdired-previous-line
        widget-kill-line
        ))

(setq mc/cmds-to-run-once
      '(
        View-scroll-page-backward
        counsel-M-x
        dap-tooltip-mouse-motion
        find-file-read-only
        gud-tooltip-mouse-motion
        handle-switch-frame
        lsp-signature-stop
        overwrite-mode
        read-only-mode
        ))
