;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-defun
        beginning-of-visual-line
        comment-dwim
        company-indent-or-complete-common
        delete-indentation
        end-of-defun
        end-of-visual-line
        goto-line
        home-end-home
        indent-for-tab-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-next-sexp
        sp-remove-active-pair-overlay
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        lsp-signature-stop
        View-scroll-page-backward
        dap-tooltip-mouse-motion
        handle-switch-frame
        read-only-mode
        ))
