;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        comment-dwim
        company-indent-or-complete-common
        end-of-visual-line
        home-end-home
        read-only-mode
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        dap-tooltip-mouse-motion
        handle-switch-frame
        ))
